import { createClientFromRequest } from 'npm:@base44/sdk@0.8.35';

// Run this function once (via Base44 invoke or local script with service role) after pushing Taxon entity.
// It is idempotent by scientific_name + type.

const SAMPLE_TAXA = [
  // === PSYCHOACTIVE FUNGI (Mushrooms) - Comprehensive list ===
  { type: 'fungus', common_name: 'Chanterelle', scientific_name: 'Cantharellus cibarius', rarity: 'common', edibility: 'safe', fruiting_season: 'summer, autumn', habitat: 'coniferous and mixed forests', key_features: ['vase-shaped', 'false gills', 'apricot smell'], associated_trees: ['pine', 'oak'] },
  { type: 'fungus', common_name: 'Fly Agaric', scientific_name: 'Amanita muscaria', rarity: 'common', edibility: 'toxic', fruiting_season: 'autumn', habitat: 'birch and pine woods', key_features: ['red cap with white warts'], toxicity_or_safety_notes: 'Psychoactive (muscimol/ibotenic acid) - toxic, do not consume', psychoactive_compounds: ['muscimol', 'ibotenic acid'], primary_effects: 'Deliriant, sedative, visionary at low doses', risk_level: 'high' },
  { type: 'fungus', common_name: 'Chicken of the Woods', scientific_name: 'Laetiporus sulphureus', rarity: 'uncommon', edibility: 'safe', fruiting_season: 'summer, autumn', habitat: 'on oak and other hardwoods', key_features: ['bright orange shelves', 'chicken-like texture when young'] },
  { type: 'fungus', common_name: 'Psilocybe Cubensis', scientific_name: 'Psilocybe cubensis', rarity: 'common', edibility: 'psychoactive', fruiting_season: 'summer, autumn', habitat: 'cow dung, pastures, subtropical', key_features: ['golden brown cap', 'purple gills', 'blue bruising'], toxicity_or_safety_notes: 'Psychedelic (psilocybin/psilocin) - powerful, set and setting critical', psychoactive_compounds: ['psilocybin', 'psilocin'], primary_effects: 'Euphoria, visuals, introspection', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Liberty Cap', scientific_name: 'Psilocybe semilanceata', rarity: 'common', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'grassy meadows, pastures', key_features: ['conical cap', 'small size', 'blue bruising'], toxicity_or_safety_notes: 'Psychedelic - common in Europe', psychoactive_compounds: ['psilocybin'], primary_effects: 'Visuals, euphoria', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Wavy Cap', scientific_name: 'Psilocybe cyanescens', rarity: 'uncommon', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'wood chips, mulch, coastal', key_features: ['wavy cap edge', 'strong blue bruising'], toxicity_or_safety_notes: 'Highly potent psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Intense visuals', risk_level: 'high' },
  { type: 'fungus', common_name: 'Azurescens', scientific_name: 'Psilocybe azurescens', rarity: 'rare', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'dune grass, wood debris', key_features: ['large caramel cap', 'intense blue bruising'], toxicity_or_safety_notes: 'One of the most potent', psychoactive_compounds: ['psilocybin'], primary_effects: 'Very strong psychedelic', risk_level: 'high' },
  { type: 'fungus', common_name: 'Blue Meanies', scientific_name: 'Panaeolus cyanescens', rarity: 'uncommon', edibility: 'psychoactive', fruiting_season: 'year-round (tropics)', habitat: 'cow dung, tropical pastures', key_features: ['thin stem', 'dark gills', 'rapid blue bruising'], toxicity_or_safety_notes: 'Very potent psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Intense, fast onset', risk_level: 'high' },
  { type: 'fungus', common_name: 'Big Laughing Gym', scientific_name: 'Gymnopilus spectabilis', rarity: 'uncommon', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'hardwood logs, stumps', key_features: ['orange cap', 'bitter taste'], toxicity_or_safety_notes: 'Psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Euphoria, laughter', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Psilocybe Mexicana', scientific_name: 'Psilocybe mexicana', rarity: 'rare', edibility: 'psychoactive', fruiting_season: 'summer, autumn', habitat: 'meadows, subtropical', key_features: ['small brown cap', 'conical shape'], toxicity_or_safety_notes: 'Traditional psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Mild to strong', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Psilocybe Baeocystis', scientific_name: 'Psilocybe baeocystis', rarity: 'uncommon', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'wood chips, lawns', key_features: ['olive-brown cap', 'wavy margin'], toxicity_or_safety_notes: 'Psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Visuals', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Psilocybe Tampanensis', scientific_name: 'Psilocybe tampanensis', rarity: 'rare', edibility: 'psychoactive', fruiting_season: 'summer, autumn', habitat: 'sandy soils, Florida', key_features: ['small cap', 'produces truffles'], toxicity_or_safety_notes: 'Produces philosopher\'s stones', psychoactive_compounds: ['psilocybin'], primary_effects: 'Mild psychedelic', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Amanita Pantherina', scientific_name: 'Amanita pantherina', rarity: 'uncommon', edibility: 'toxic', fruiting_season: 'summer, autumn', habitat: 'coniferous and mixed forests', key_features: ['brown cap', 'white warts'], toxicity_or_safety_notes: 'Psychoactive but highly toxic - avoid', psychoactive_compounds: ['muscimol'], primary_effects: 'Deliriant', risk_level: 'extreme' },
  { type: 'fungus', common_name: 'Psilocybe Caerulipes', scientific_name: 'Psilocybe caerulipes', rarity: 'rare', edibility: 'psychoactive', fruiting_season: 'autumn', habitat: 'hardwood debris', key_features: ['small blue foot'], toxicity_or_safety_notes: 'Psychedelic', psychoactive_compounds: ['psilocybin'], primary_effects: 'Mild visuals', risk_level: 'medium' },
  { type: 'fungus', common_name: 'Psilocybe Hoogshagenii', scientific_name: 'Psilocybe hoogshagenii', rarity: 'rare', edibility: 'psychoactive', fruiting_season: 'summer, autumn', habitat: 'meadows, Mexico', key_features: ['conical cap'], toxicity_or_safety_notes: 'Traditional use', psychoactive_compounds: ['psilocybin'], primary_effects: 'Visionary', risk_level: 'medium' },

  // === PSYCHOACTIVE PLANTS - Comprehensive ===
  { type: 'plant', common_name: 'Cannabis', scientific_name: 'Cannabis sativa', rarity: 'common', traditional_uses: ['recreation', 'medicine', 'fiber'], habitat: 'cultivated worldwide', flowering_or_fruiting_season: 'summer, autumn', phytochemical_notes: 'THC, CBD', cultural_significance: 'Widely used for millennia', psychoactive_compounds: ['THC', 'CBD'], primary_effects: 'Euphoria, relaxation, altered perception', risk_level: 'low' },
  { type: 'plant', common_name: 'Opium Poppy', scientific_name: 'Papaver somniferum', rarity: 'common', traditional_uses: ['pain relief', 'sedation'], habitat: 'cultivated fields', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'Morphine, codeine', psychoactive_compounds: ['morphine', 'codeine'], primary_effects: 'Euphoria, pain relief, sedation', risk_level: 'high' },
  { type: 'plant', common_name: 'Coca', scientific_name: 'Erythroxylum coca', rarity: 'uncommon', traditional_uses: ['energy', 'appetite suppression'], habitat: 'Andean slopes', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Cocaine', psychoactive_compounds: ['cocaine'], primary_effects: 'Stimulant, euphoria', risk_level: 'high' },
  { type: 'plant', common_name: 'Peyote', scientific_name: 'Lophophora williamsii', rarity: 'rare', traditional_uses: ['visionary', 'healing'], habitat: 'desert, limestone soils', flowering_or_fruiting_season: 'spring, summer', phytochemical_notes: 'Mescaline', psychoactive_compounds: ['mescaline'], primary_effects: 'Visionary, introspection', risk_level: 'medium' },
  { type: 'plant', common_name: 'San Pedro', scientific_name: 'Trichocereus pachanoi', rarity: 'uncommon', traditional_uses: ['healing', 'divination'], habitat: 'Andes, cultivated', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'Mescaline', psychoactive_compounds: ['mescaline'], primary_effects: 'Visionary', risk_level: 'medium' },
  { type: 'plant', common_name: 'Ayahuasca Vine', scientific_name: 'Banisteriopsis caapi', rarity: 'uncommon', traditional_uses: ['visionary journeys'], habitat: 'Amazon rainforest', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Harmine, harmaline (MAOI)', psychoactive_compounds: ['harmine', 'harmaline'], primary_effects: 'MAOI - enables DMT', risk_level: 'medium' },
  { type: 'plant', common_name: 'Chacruna', scientific_name: 'Psychotria viridis', rarity: 'uncommon', traditional_uses: ['DMT source in ayahuasca'], habitat: 'Amazon understory', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'DMT', psychoactive_compounds: ['DMT'], primary_effects: 'Visionary (with MAOI)', risk_level: 'medium' },
  { type: 'plant', common_name: "Diviner's Sage", scientific_name: 'Salvia divinorum', rarity: 'rare', traditional_uses: ['divination'], habitat: 'Oaxaca cloud forests', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Salvinorin A', psychoactive_compounds: ['salvinorin A'], primary_effects: 'Intense short visionary', risk_level: 'high' },
  { type: 'plant', common_name: 'Iboga', scientific_name: 'Tabernanthe iboga', rarity: 'rare', traditional_uses: ['initiation', 'addiction treatment'], habitat: 'Gabon rainforests', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Ibogaine', psychoactive_compounds: ['ibogaine'], primary_effects: 'Oneirogen, introspection', risk_level: 'high' },
  { type: 'plant', common_name: 'Kratom', scientific_name: 'Mitragyna speciosa', rarity: 'common', traditional_uses: ['energy', 'pain'], habitat: 'tropical wetlands SE Asia', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Mitragynine', psychoactive_compounds: ['mitragynine', '7-hydroxymitragynine'], primary_effects: 'Stimulant low dose, opioid-like high dose', risk_level: 'medium' },
  { type: 'plant', common_name: 'Jimsonweed', scientific_name: 'Datura stramonium', rarity: 'common', traditional_uses: ['ritual (risky)'], habitat: 'disturbed soils', flowering_or_fruiting_season: 'summer, autumn', phytochemical_notes: 'Scopolamine, atropine', psychoactive_compounds: ['scopolamine', 'atropine'], primary_effects: 'Deliriant, dangerous', risk_level: 'extreme' },
  { type: 'plant', common_name: "Angels Trumpet", scientific_name: 'Brugmansia suaveolens', rarity: 'uncommon', traditional_uses: ['shamanic (highly dangerous)'], habitat: 'cultivated, Andean origins', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Tropane alkaloids', psychoactive_compounds: ['scopolamine'], primary_effects: 'Deliriant', risk_level: 'extreme' },
  { type: 'plant', common_name: 'Hawaiian Baby Woodrose', scientific_name: 'Argyreia nervosa', rarity: 'uncommon', traditional_uses: ['entheogen'], habitat: 'cultivated tropics', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'LSA (ergine)', psychoactive_compounds: ['LSA'], primary_effects: 'LSD-like but milder, longer', risk_level: 'medium' },
  { type: 'plant', common_name: 'Morning Glory', scientific_name: 'Ipomoea tricolor', rarity: 'common', traditional_uses: ['traditional Mesoamerican'], habitat: 'gardens, disturbed', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'LSA', psychoactive_compounds: ['LSA'], primary_effects: 'Mild psychedelic', risk_level: 'medium' },
  { type: 'plant', common_name: 'Wild Tobacco', scientific_name: 'Nicotiana rustica', rarity: 'common', traditional_uses: ['ritual, shamanic'], habitat: 'cultivated, disturbed', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'High nicotine', psychoactive_compounds: ['nicotine'], primary_effects: 'Strong stimulant, ritual', risk_level: 'high' },
  { type: 'plant', common_name: 'Betel Nut', scientific_name: 'Areca catechu', rarity: 'common', traditional_uses: ['social stimulant Asia'], habitat: 'palm groves', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Arecoline', psychoactive_compounds: ['arecoline'], primary_effects: 'Mild stimulant, euphoria', risk_level: 'medium' },
  { type: 'plant', common_name: 'Kava', scientific_name: 'Piper methysticum', rarity: 'common', traditional_uses: ['social, ceremony Pacific'], habitat: 'Pacific islands', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Kavalactones', psychoactive_compounds: ['kavalactones'], primary_effects: 'Relaxation, anxiety relief', risk_level: 'low' },
  { type: 'plant', common_name: 'Khat', scientific_name: 'Catha edulis', rarity: 'common', traditional_uses: ['social stimulant Horn of Africa'], habitat: 'Horn of Africa, Arabia', flowering_or_fruiting_season: 'year-round', phytochemical_notes: 'Cathinone', psychoactive_compounds: ['cathinone'], primary_effects: 'Amphetamine-like stimulant', risk_level: 'medium' },
  { type: 'plant', common_name: 'Ephedra', scientific_name: 'Ephedra sinica', rarity: 'common', traditional_uses: ['stimulant, traditional Chinese'], habitat: 'dry regions', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'Ephedrine', psychoactive_compounds: ['ephedrine'], primary_effects: 'Stimulant', risk_level: 'medium' },
  { type: 'plant', common_name: 'Ashwagandha', scientific_name: 'Withania somnifera', rarity: 'common', traditional_uses: ['adaptogen, Ayurvedic'], habitat: 'dry regions India', flowering_or_fruiting_season: 'summer, autumn', phytochemical_notes: 'Withanolides', psychoactive_compounds: [], primary_effects: 'Stress relief, not strongly psychoactive', risk_level: 'low' },

  // More ethnobotanical for completeness
  { type: 'plant', common_name: 'Yarrow', scientific_name: 'Achillea millefolium', rarity: 'common', traditional_uses: ['wound healing', 'fever', 'digestion'], habitat: 'meadows, roadsides', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'Achilleine', cultural_significance: 'European folk medicine' },
  { type: 'plant', common_name: "St. John's Wort", scientific_name: 'Hypericum perforatum', rarity: 'common', traditional_uses: ['mood support', 'wound care'], habitat: 'dry grasslands', flowering_or_fruiting_season: 'summer', phytochemical_notes: 'Hypericin, hyperforin' },
  { type: 'plant', common_name: 'Elderberry', scientific_name: 'Sambucus nigra', rarity: 'common', traditional_uses: ['immune support', 'coughs'], habitat: 'hedgerows', flowering_or_fruiting_season: 'late summer' },
  { type: 'plant', common_name: 'Nettle', scientific_name: 'Urtica dioica', rarity: 'common', traditional_uses: ['nutrient tonic', 'allergy relief'], habitat: 'rich soil', flowering_or_fruiting_season: 'spring, summer' },
  { type: 'plant', common_name: 'Mugwort', scientific_name: 'Artemisia vulgaris', rarity: 'common', traditional_uses: ['digestion', 'dream work'], habitat: 'roadsides', flowering_or_fruiting_season: 'summer, autumn' },
  { type: 'plant', common_name: 'Dandelion', scientific_name: 'Taraxacum officinale', rarity: 'common', traditional_uses: ['liver support', 'food'], habitat: 'lawns, fields', flowering_or_fruiting_season: 'spring, summer' },
  { type: 'plant', common_name: 'Plantain', scientific_name: 'Plantago major', rarity: 'common', traditional_uses: ['wounds', 'respiratory'], habitat: 'paths, compacted soil', flowering_or_fruiting_season: 'summer' },
  { type: 'plant', common_name: 'Turmeric', scientific_name: 'Curcuma longa', rarity: 'common', traditional_uses: ['anti-inflammatory', 'dye', 'food'], habitat: 'tropics', flowering_or_fruiting_season: 'summer' },
  { type: 'plant', common_name: 'Ginseng', scientific_name: 'Panax ginseng', rarity: 'uncommon', traditional_uses: ['vitality', 'longevity'], habitat: 'mountain forests Asia', flowering_or_fruiting_season: 'autumn' },
  { type: 'plant', common_name: 'Valerian', scientific_name: 'Valeriana officinalis', rarity: 'common', traditional_uses: ['sleep', 'anxiety'], habitat: 'damp meadows', flowering_or_fruiting_season: 'summer' },
  { type: 'plant', common_name: 'Echinacea', scientific_name: 'Echinacea purpurea', rarity: 'common', traditional_uses: ['immune support'], habitat: 'prairies North America', flowering_or_fruiting_season: 'summer' },
  { type: 'plant', common_name: 'Calea Zacatechichi', scientific_name: 'Calea ternifolia', rarity: 'uncommon', traditional_uses: ['dream herb'], habitat: 'Mexico', flowering_or_fruiting_season: 'summer', psychoactive_compounds: ['germacrene'], primary_effects: 'Vivid dreams', risk_level: 'low' },
  { type: 'plant', common_name: 'Sinicuichi', scientific_name: 'Heimia salicifolia', rarity: 'uncommon', traditional_uses: ['auditory hallucinations'], habitat: 'Mexico', flowering_or_fruiting_season: 'summer', psychoactive_compounds: ['cryogenine'], primary_effects: 'Yellow vision, echoes', risk_level: 'medium' }
];

Deno.serve(async (req) => {
  const base44 = createClientFromRequest(req);
  const sr = base44.asServiceRole || base44;

  const results = [];
  for (const sample of SAMPLE_TAXA) {
    const existing = await sr.entities.Taxon.list({
      filter: { scientific_name: sample.scientific_name, type: sample.type }
    });

    if (existing.length === 0) {
      const created = await sr.entities.Taxon.create({
        ...sample,
        source: 'seedTaxa',
        last_enriched: new Date().toISOString(),
        is_active: true
      });
      results.push({ action: 'created', id: created.id, scientific_name: sample.scientific_name });
    } else {
      results.push({ action: 'exists', id: existing[0].id, scientific_name: sample.scientific_name });
    }
  }

  return Response.json({ success: true, seeded: results.length, details: results });
});